version: '3.7'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: uTXa3ZqJ1DMHR9WypFboLgYcKsvfNe58
      MYSQL_DATABASE: library
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - library_network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  elasticsearch_data:
    driver: local
  mysql_data:
    driver: local

networks:
  library_network:
    driver: bridge
